articles/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.conf.urls import url
from articles.views import ArticleDetailView, ArticleListView

urlpatterns = [
    url(r'^$', ArticleListView.as_view(), name='article-list'),
    url(r'^(?P<slug>[\w-]+)/$', ArticleDetailView.as_view(), name='article-detail'),
]

articles/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.utils.encoding import python_2_unicode_compatible
from django.db import models
from django.utils.translation import ugettext_lazy as _
from oscar.models.fields import AutoSlugField
from redactor.fields import RedactorField
from sorl.thumbnail import ImageField


@python_2_unicode_compatible
class Article(models.Model):
    title = models.CharField('Заголовок', max_length=255)
    image = ImageField('Изображение', upload_to='articles/%Y/%m/%d/')
    text_short = models.TextField(verbose_name='Краткое содержание')
    text = RedactorField(verbose_name='Текст статьи')
    date_created = models.DateTimeField('Дата добавления', auto_now_add=True)
    date_update = models.DateTimeField('Дата обновления', auto_now=True)
    is_active = models.BooleanField('Опубликована', default=True)
    slug = AutoSlugField(_('Slug'), max_length=128, unique=True,
                         populate_from='title')
    views = models.PositiveIntegerField('Количество просмотров', default=0)

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'
        ordering = ['-date_created']

    def __str__(self):
        return self.title

    @models.permalink
    def get_absolute_url(self):
        return ('article-detail', (), {'slug': self.slug})

dashboard/articles/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import
from django import forms
from redactor.widgets import RedactorEditor
from articles.models import Article


class ArticleUpdateForm(forms.ModelForm):
    class Meta:
        model = Article
        exclude = ['views']
        widgets = {
            'text': RedactorEditor()
        }

    class Media:
        css = {
            'all': ('dashboard/redactor.css',)
        }

dashboard/catalogue/forms.py
from django import forms
from treebeard.forms import movenodeform_factory
from oscar.core.loading import get_model
from oscar.apps.dashboard.catalogue.forms import ProductForm as CoreProductForm


Category = get_model('catalogue', 'Category')
Product = get_model('catalogue', 'Product')

CategoryForm = movenodeform_factory(
    Category,
    fields=['name', 'description', 'image', 'product_class'])


class ProductForm(CoreProductForm):
    class Meta(CoreProductForm.Meta):
        fields = CoreProductForm.Meta.fields + ['short_description']

dashboard/pages/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import
from django import forms
from oscar.apps.dashboard.pages import forms as pages_forms
from redactor.widgets import RedactorEditor


class PageUpdateForm(pages_forms.PageUpdateForm):
    class Meta(pages_forms.PageUpdateForm.Meta):
        widgets = {
            'content': RedactorEditor()
        }

    class Media:
        css = {
            'all': ('dashboard/redactor.css',)
        }

dashboard/slider/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django import forms
from treebeard.forms import movenodeform_factory
from slider.models import Slide


# class SlideForm(forms.ModelForm):
#     class Meta:
#         model = Slide
#         fields = ['image', 'title']
SlideForm = movenodeform_factory(
    Slide,
    fields=['image', 'title']
)

articles/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.views import generic
from articles.models import Article


class ArticleDetailView(generic.DetailView):
    queryset = Article.objects.filter(is_active=True)


class ArticleListView(generic.ListView):
    queryset = Article.objects.filter(is_active=True)
    paginate_by = 20

dashboard/articles/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import
from django.conf import settings
from django.core.urlresolvers import reverse_lazy
from django.views import generic
from django.views.generic import ListView

from articles.models import Article
from .forms import ArticleUpdateForm


class ArticleListView(ListView):
    template_name = 'dashboard/articles/index.html'
    model = Article
    paginate_by = settings.OSCAR_DASHBOARD_ITEMS_PER_PAGE


class ArticleCreateView(generic.CreateView):
    template_name = 'dashboard/articles/update.html'
    model = Article
    form_class = ArticleUpdateForm
    context_object_name = 'article'
    success_url = reverse_lazy('dashboard:article-list')

    def get_context_data(self, **kwargs):
        ctx = super(ArticleCreateView, self).get_context_data(**kwargs)
        ctx['title'] = 'Добавить статью'
        return ctx


class ArticleUpdateView(generic.UpdateView):
    template_name = 'dashboard/articles/update.html'
    model = Article
    form_class = ArticleUpdateForm
    context_object_name = 'article'
    success_url = reverse_lazy('dashboard:article-list')

    def get_context_data(self, **kwargs):
        ctx = super(ArticleUpdateView, self).get_context_data(**kwargs)
        ctx['title'] = self.object.title
        return ctx


class ArticleDeleteView(generic.DeleteView):
    template_name = 'dashboard/articles/delete.html'
    model = Article
    success_url = reverse_lazy('dashboard:article-list')

dashboard/pages/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import
from oscar.apps.dashboard.pages import views
from .forms import PageUpdateForm


class PageCreateView(views.PageCreateView):
    form_class = PageUpdateForm


class PageUpdateView(views.PageUpdateView):
    form_class = PageUpdateForm

dashboard/settings/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from operator import itemgetter
from django.urls import reverse_lazy
from django.views.generic import FormView
from django.utils.formats import localize
from constance.admin import ConstanceForm, get_values
from constance import config, settings


class SettingsView(FormView):
    template_name = 'settings/settings.html'
    form_class = ConstanceForm
    success_url = reverse_lazy('dashboard:settings')

    def __init__(self, *args, **kwargs):
        if 'fields' in kwargs:
            self.fields = kwargs.pop('fields')
        else:
            self.fields = settings.CONFIG.keys()
        super(SettingsView, self).__init__(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(SettingsView, self).get_context_data(**kwargs)
        context['settings'] = []
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        initial = self.get_initial()
        for name, options in settings.CONFIG.items():
            default, help_text = options[0], options[1]
            value = initial.get(name)
            if value is None:
                value = getattr(config, name)

            context['settings'].append({
                'name': name,
                'default': localize(default),
                'help_text': help_text,
                'value': localize(value),
                'modified': value != default,
                'form_field': form[name],
            })
        context['settings'].sort(key=itemgetter('name'))
        return context

    def get_initial(self):
        data = super(SettingsView, self).get_initial()
        data.update(get_values())
        return data

    def form_valid(self, form):
        form.save()
        return self.render_to_response(self.get_context_data(form=form, success_save='ok'))

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form, success_save='error'))

dashboard/slider/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, CreateView, TemplateView, DeleteView, UpdateView
from django_tables2 import SingleTableMixin
from slider.models import Slide
from .forms import SlideForm
from .tables import SliderTable


class SlideListView(SingleTableMixin, TemplateView):
    template_name = 'dashboard/slider/slide_list.html'
    context_table_name = 'slides'
    table_class = SliderTable
    table_data = Slide.objects.all()


class SlideCreateView(CreateView):
    model = Slide
    template_name = 'dashboard/slider/slide_form.html'
    form = SlideForm
    fields = '__all__'
    success_url = reverse_lazy('dashboard:slide-list')

    def get_context_data(self, **kwargs):
        ctx = super(SlideCreateView, self).get_context_data(**kwargs)
        ctx['title'] = 'Добавить слайд'
        return ctx


class SlideUpdateView(UpdateView):
    model = Slide
    template_name = 'dashboard/slider/slide_form.html'
    form = SlideForm
    fields = '__all__'
    success_url = reverse_lazy('dashboard:slide-list')

    def get_context_data(self, **kwargs):
        ctx = super(SlideUpdateView, self).get_context_data(**kwargs)
        ctx['title'] = 'Изменить слайд %s' % self.object.title
        return ctx


class SlideDeleteView(DeleteView):
    model = Slide
    template_name = 'dashboard/slider/slide_delete.html'
    success_url = reverse_lazy('dashboard:slide-list')

    def get_context_data(self, **kwargs):
        ctx = super(SlideDeleteView, self).get_context_data(**kwargs)
        ctx['title'] = 'Удалить слайд %s' % self.object.title
        return ctx

templates/dashboard/articles/delete.html
{% extends 'dashboard/layout.html' %}
{% load i18n %}

{% block body_class %}{{ block.super }} articles delete-article{% endblock %}

{% block title %}
    Удалить статью '{{ title }}'? | {{ block.super }}
{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumb">
        <li>
            <a href="{% url 'dashboard:index' %}">{% trans "Dashboard" %}</a>
        </li>
        <li>
            <a href="{% url 'dashboard:article-list' %}">Статьи</a>
        </li>
        <li class="active">Удалить статью '{{ object.title }}'?</li>
    </ul>
{% endblock %}

{% block headertext %}
    Удалить статью '{{ object.title }}'?
{% endblock %}

{% block dashboard_content %}
    <div class="table-header">
        <h2>Удалить статью</h2>
    </div>
    <form action="." method="post" class="well">
        {% csrf_token %}
        {{ form }}
        <p>Удалить статью <strong>{{ object.title }}</strong> - вы уверены?</p>
        <div class="form-actions">
            <button type="submit" class="btn btn-danger" data-loading-text="{% trans 'Deleting...' %}">{% trans "Delete" %}</button>
            {% trans "or" %} <a href="{% url 'dashboard:article-list' %}">{% trans "cancel" %}</a>.
        </div>
    </form>
{% endblock %}

templates/dashboard/articles/index.html
{% extends 'dashboard/layout.html' %}
{% load dashboard_tags %}
{% load i18n %}

{% block body_class %}{{ block.super }} articles{% endblock %}

{% block title %}
    Статьи | {{ block.super }}
{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumb">
        <li>
            <a href="{% url 'dashboard:index' %}">{% trans "Dashboard" %}</a>
        </li>
        <li class="active">Статьи</li>
    </ul>
{% endblock %}

{% block header %}
    <div class="article-header">
        <a href="{% url 'dashboard:article-create' %}" class="btn btn-primary btn-lg pull-right"><i class="icon-plus"></i> Добавить статью</a>
        <h1>Статьи</h1>
    </div>
{% endblock header %}

{% block dashboard_content %}
    <div class="table-header">
        <h2><i class="icon-file icon-large"></i>Статьи</h2>
    </div>


    {% if article_list %}
        <form action="." method="post">
            {% csrf_token %}
            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th>Заголовок</th>
                        <th>URL</th>
                        <th>Дата публикации</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for article in article_list %}
                        <tr>
                            <td><a href="{% url 'dashboard:article-update' pk=article.id %}">{{ article.title}}</a></td>
                            <td><a title="{% trans "View on site" %}" href="{{ article.get_absolute_url }}">{{ article.get_absolute_url }}</a></td>
                            <td>{{ article.date_created }}</td>
                            <td>
                                <div class="btn-toolbar">
                                    <div class="btn-group">
                                        <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="true">
                                            {% trans "Actions" %}
                                            <span class="caret"></span>
                                        </button>
                                        <ul class="dropdown-menu pull-right">
                                            <li><a href="{{ article.get_absolute_url }}">{% trans "View" %}</a></li>
                                            <li><a id="edit_article_{{ article.id }}" href="{% url 'dashboard:article-update' pk=article.id %}">{% trans "Edit" %}</a></li>
                                            <li><a id="delete_article_{{ article.id }}" href="{% url 'dashboard:article-delete' pk=article.id %}">{% trans "Delete" %}</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% include "dashboard/partials/pagination.html" %}
        </form>
    {% else %}
        <table class="table table-striped table-bordered table-hover">
            <tr><td>{% trans "No articles found." %}</td></tr>
        </table>
    {% endif %}

{% endblock dashboard_content %}

{% block onbodyload %}
    {{ block.super }}
    oscar.dashboard.search.init();
{% endblock onbodyload %}

templates/dashboard/articles/update.html
{% extends 'dashboard/layout.html' %}

{% load i18n %}

{% block body_class %}{{ block.super }} articles create-page{% endblock %}
{% block title %}
{{ title }} | {{ block.super }}
{% endblock %}

{% block extrastyles %}
    {{ block.super }}
    {{ form.media.css }}
{% endblock %}

{% block extrascripts %}
    {{ block.super }}
    {{ form.media.js }}
{% endblock %}

{% block breadcrumbs %}
<ul class="breadcrumb">
    <li>
        <a href="{% url 'dashboard:index' %}">{% trans "Dashboard" %}</a>
    </li>
    <li>
        <a href="{% url 'dashboard:article-list' %}">Статьи</a>
    </li>
    <li class="active">{{ title }}</li>
</ul>
{% endblock %}

{% block headertext %}
{{ title }}
{% endblock %}

{% block dashboard_content %}
<div class="table-header">
    <h2>{{ title }}</h2>
</div>

<form action="." method="post" class="well form-stacked" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'dashboard/partials/form_fields.html' with form=form %}
    <div class="form-actions">
        <button class="btn btn-lg btn-primary" type="submit" data-loading-text="{% trans 'Saving...' %}">{% trans "Save" %}</button>
        {% trans "or" %} <a href="{% url 'dashboard:article-list' %}">{% trans "cancel" %}</a>.
    </div>
</form>

{% endblock dashboard_content %}